# Generated by Django 3.1.4 on 2021-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpageviewkeybenfitsmodel',
            name='sort_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='key benfit sort id'),
        ),
    ]
