# Generated by Django 3.1.4 on 2021-04-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_auto_20210420_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpageviewkeybenfitsmodel',
            name='keybenfit_video_url',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Key benfit video url'),
        ),
    ]
