# Generated by Django 3.1.4 on 2021-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_auto_20210420_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexNavbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('sort_id', models.IntegerField(db_index=True, default=0, verbose_name='Navbar sort id')),
                ('navbar_title', models.CharField(default='', max_length=16, verbose_name='Navbar title')),
                ('navbar_url', models.CharField(blank=True, default='', max_length=256, verbose_name='Navbar url')),
                ('navbar_icon', models.CharField(blank=True, default='', max_length=32, verbose_name='Navbar icon')),
            ],
            options={
                'verbose_name': 'navbar',
                'verbose_name_plural': 'navbar',
                'db_table': 'armod_index_navbar',
            },
        ),
    ]
