# Generated by Django 3.1.6 on 2021-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_indexnavbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('header_name', models.CharField(default='', max_length=16, verbose_name='Header name')),
                ('header_descript', models.CharField(default='', max_length=16, verbose_name='Header descript name')),
                ('header_download_url', models.CharField(default='', max_length=16, verbose_name='Header download url')),
                ('header_video_url', models.CharField(blank=True, default='', max_length=256, verbose_name='Header Video url')),
            ],
            options={
                'verbose_name': 'header',
                'verbose_name_plural': 'header',
                'db_table': 'armod_index_header',
            },
        ),
        migrations.CreateModel(
            name='IndexVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('video_name', models.CharField(default='', max_length=16, verbose_name='Video name')),
                ('video_url', models.CharField(blank=True, default='', max_length=256, verbose_name='Video url')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'video',
                'db_table': 'armod_index_video',
            },
        ),
        migrations.AddField(
            model_name='indexpageviewkeybenfitsmodel',
            name='keybenfit_type',
            field=models.IntegerField(default=0, verbose_name='Key benfit type'),
        ),
    ]
