# Generated by Django 3.1.6 on 2021-05-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0006_auto_20210502_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexVideos',
        ),
    ]
