# Generated by Django 3.1.6 on 2021-05-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0007_delete_indexvideos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexheader',
            name='header_download_url',
        ),
        migrations.AddField(
            model_name='indexheader',
            name='header_lead_image',
            field=models.CharField(default='', max_length=256, verbose_name='Header Lead Image url'),
        ),
        migrations.AddField(
            model_name='indexheader',
            name='header_video_bg_url',
            field=models.CharField(default='', max_length=256, verbose_name='Header Video bg url'),
        ),
        migrations.AlterField(
            model_name='indexheader',
            name='header_video_url',
            field=models.CharField(default='', max_length=256, verbose_name='Header Video url'),
        ),
    ]
