# Generated by Django 3.1.6 on 2021-05-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0008_auto_20210502_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexGuid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('guid_selection', models.CharField(default='', max_length=16, verbose_name='Header name')),
                ('guid_video_url', models.CharField(default='', max_length=256, verbose_name='Header name')),
                ('guidtype', models.IntegerField(default=0, verbose_name='Key benfit type')),
                ('guid_guid_description', models.CharField(default='', max_length=1024, verbose_name='Header name')),
                ('guid_title', models.CharField(default='', max_length=16, verbose_name='Header name')),
            ],
            options={
                'verbose_name': 'Index Guid',
                'verbose_name_plural': 'Index Guid',
                'db_table': 'armod_index_guid',
            },
        ),
    ]
