# Generated by Django 3.2 on 2021-05-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0009_indexguid'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexnavbar',
            name='navbar_subs',
            field=models.JSONField(default=[], verbose_name='Navbar url'),
        ),
    ]
