# Generated by Django 3.2 on 2021-05-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0011_alter_indexnavbar_navbar_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexnavbar',
            name='navbar_subs',
            field=models.JSONField(blank=True, default=[], verbose_name='Navbar subs'),
        ),
    ]
