# Generated by Django 3.2 on 2021-05-04 10:34

import Apps.Index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0012_alter_indexnavbar_navbar_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexguid',
            name='guid_guid_description',
        ),
        migrations.RemoveField(
            model_name='indexguid',
            name='guid_title',
        ),
        migrations.RemoveField(
            model_name='indexguid',
            name='guid_video_url',
        ),
        migrations.AddField(
            model_name='indexguid',
            name='guid_subs',
            field=models.JSONField(default=Apps.Index.models.getJSONFieldDefault, verbose_name='guid subs'),
        ),
        migrations.AddField(
            model_name='indexnavbar',
            name='navbar_display',
            field=models.BooleanField(default=True, verbose_name='Navbar status'),
        ),
        migrations.AlterField(
            model_name='indexnavbar',
            name='navbar_subs',
            field=models.JSONField(blank=True, default=Apps.Index.models.getJSONFieldDefault, verbose_name='Navbar subs'),
        ),
    ]
