# Generated by Django 3.2 on 2021-05-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0014_indexheader_header_copyright_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexheader',
            name='header_copyright_info',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Header copryright info'),
        ),
    ]
