# Generated by Django 3.2 on 2021-05-04 14:05

import Apps.Index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0015_alter_indexheader_header_copyright_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexguid',
            options={'verbose_name': 'Index Guides', 'verbose_name_plural': 'Index Guides'},
        ),
        migrations.RemoveField(
            model_name='indexguid',
            name='guid_selection',
        ),
        migrations.RemoveField(
            model_name='indexguid',
            name='guid_subs',
        ),
        migrations.RemoveField(
            model_name='indexguid',
            name='guidtype',
        ),
        migrations.AddField(
            model_name='indexguid',
            name='guide_selection',
            field=models.CharField(default='', max_length=16, verbose_name='guide name'),
        ),
        migrations.AddField(
            model_name='indexguid',
            name='guide_type',
            field=models.IntegerField(default=0, verbose_name='guide type'),
        ),
        migrations.AddField(
            model_name='indexguid',
            name='guides_subs',
            field=models.JSONField(default=Apps.Index.models.getJSONFieldDefault, verbose_name='guides subs'),
        ),
        migrations.AlterModelTable(
            name='indexguid',
            table='armod_index_guides',
        ),
    ]
