# Generated by Django 3.2 on 2021-05-04 14:27

import Apps.Index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0016_auto_20210504_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexguid',
            name='guides_subs',
        ),
        migrations.AddField(
            model_name='indexguid',
            name='guide_display',
            field=models.BooleanField(default=True, verbose_name='guide status'),
        ),
        migrations.AddField(
            model_name='indexguid',
            name='guide_subs',
            field=models.JSONField(default=Apps.Index.models.getJSONFieldDefault, verbose_name='guide subs'),
        ),
    ]
