# Generated by Django 3.2 on 2021-05-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0017_auto_20210504_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexGuid',
            new_name='IndexGuides',
        ),
    ]
