# Generated by Django 3.2 on 2021-05-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0018_rename_indexguid_indexguides'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexheader',
            name='header_download_title',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Header download title'),
        ),
        migrations.AddField(
            model_name='indexheader',
            name='header_download_url',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Header download url'),
        ),
       
        migrations.AlterField(
            model_name='indexheader',
            name='header_descript',
            field=models.CharField(default='', max_length=64, verbose_name='Header descript name'),
        ),
    ]
