# Generated by Django 3.2 on 2021-05-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0019_auto_20210505_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexheader',
            name='header_name',
            field=models.CharField(
                default='', max_length=64, verbose_name='Header name'),
        ),

    ]
