# Generated by Django 3.2 on 2021-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0020_alter_indexheader_header_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexheader',
            name='header_showcase_descript',
            field=models.CharField(default='', max_length=256, verbose_name='Header showcase descript'),
        ),
        migrations.AddField(
            model_name='indexheader',
            name='header_showcase_title',
            field=models.CharField(default='', max_length=64, verbose_name='Header showcase title'),
        ),
    ]
