# Generated by Django 3.2 on 2021-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0021_auto_20210509_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexheader',
            name='header_showcase_descript',
            field=models.CharField(default='', max_length=512, verbose_name='Header showcase descript'),
        ),
    ]
