# Generated by Django 3.2 on 2022-02-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0022_alter_indexheader_header_showcase_descript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexheader',
            name='header_copyright_info',
        ),
        migrations.RemoveField(
            model_name='indexheader',
            name='header_lead_image',
        ),
        migrations.RemoveField(
            model_name='indexheader',
            name='header_showcase_descript',
        ),
        migrations.RemoveField(
            model_name='indexheader',
            name='header_showcase_title',
        ),
        migrations.RemoveField(
            model_name='indexheader',
            name='header_video_bg_url',
        ),
        migrations.RemoveField(
            model_name='indexheader',
            name='header_video_url',
        ),
        migrations.RemoveField(
            model_name='indexnavbar',
            name='navbar_subs',
        ),
        migrations.AddField(
            model_name='indexheader',
            name='header_brief',
            field=models.CharField(default='', max_length=128, verbose_name='Header descript name'),
        ),
        migrations.AlterField(
            model_name='indexheader',
            name='header_descript',
            field=models.CharField(default='', max_length=512, verbose_name='Header descript name'),
        ),
        migrations.AlterModelTable(
            name='indexheader',
            table='armod_index_header_test',
        ),
        migrations.AlterModelTable(
            name='indexnavbar',
            table='armod_index_navbar_test',
        ),
    ]
