# Generated by Django 3.2 on 2022-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0023_auto_20220214_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexheader',
            name='header_brief',
            field=models.CharField(default='', max_length=128, verbose_name='Header brief name'),
        ),
    ]
