# Generated by Django 3.2 on 2022-02-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0024_alter_indexheader_header_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageViewMainKeyBenfitsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('sort_id', models.IntegerField(db_index=True, default=0, verbose_name='Key benfit sort id')),
                ('keybenfit_title', models.CharField(default='', max_length=64, unique=True, verbose_name='Key benfit title')),
                ('keybenfit_description', models.CharField(default='', max_length=1024, verbose_name='Key benfit description')),
                ('keybenfit_icon', models.CharField(blank=True, default='', max_length=32, verbose_name='Key benfit icon')),
            ],
            options={
                'verbose_name': 'Index Main Keybenfits',
                'verbose_name_plural': 'Index Main Keybenfits',
                'db_table': 'armod_index_main_key_benfits',
            },
        ),
    ]
