# Generated by Django 3.2 on 2022-02-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0025_indexpageviewmainkeybenfitsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexGuideFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('guide_feature_icon', models.CharField(default='', max_length=16, verbose_name='guide feature icon')),
                ('guide_feature_name', models.CharField(default='', max_length=32, verbose_name='guide feature name')),
                ('guide_feature_description', models.CharField(default='', max_length=512, verbose_name='guide feature description')),
                ('guide_feature_tags', models.CharField(default='', max_length=512, verbose_name='guide feature tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='indexguides',
            name='guide_display',
        ),
        migrations.RemoveField(
            model_name='indexguides',
            name='guide_subs',
        ),
        migrations.RemoveField(
            model_name='indexguides',
            name='guide_type',
        ),
        migrations.AddField(
            model_name='indexguides',
            name='guid_description',
            field=models.CharField(default='', max_length=512, verbose_name='guide description'),
        ),
    ]
