# Generated by Django 3.2 on 2022-02-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0026_auto_20220214_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexguidefeatures',
            name='guide_feature_tags',
        ),
    ]
