# Generated by Django 3.2 on 2022-02-14 16:00

import Apps.Index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0027_remove_indexguidefeatures_guide_feature_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexguidefeatures',
            name='guide_feature_tags',
            field=models.JSONField(default=Apps.Index.models.getJSONFieldDefault, verbose_name='guide feature tags'),
        ),
    ]
