# Generated by Django 3.2 on 2022-02-15 03:00

import Apps.Index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0030_alter_indexguidefeatures_guide_feature_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpageviewmainkeybenfitsmodel',
            name='keybenfit_icon',
        ),
        migrations.AddField(
            model_name='indexpageviewmainkeybenfitsmodel',
            name='keybenfit_tags',
            field=models.JSONField(default=Apps.Index.models.getJSONFieldDefault, verbose_name='Key benfit tags'),
        ),
    ]
