# Generated by Django 3.2 on 2022-02-15 03:07

import Apps.Index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0031_auto_20220215_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpageviewkeybenfitsmodel',
            name='keybenfit_type',
        ),
        migrations.RemoveField(
            model_name='indexpageviewkeybenfitsmodel',
            name='keybenfit_video_url',
        ),
        migrations.AddField(
            model_name='indexpageviewkeybenfitsmodel',
            name='keybenfit_preview_url',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Key benfit preview url'),
        ),
        migrations.AddField(
            model_name='indexpageviewkeybenfitsmodel',
            name='keybenfit_tags',
            field=models.JSONField(default=Apps.Index.models.getJSONFieldDefault, verbose_name='Key benfit tags'),
        ),
    ]
