# Generated by Django 3.2 on 2022-02-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0032_auto_20220215_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpageviewmainkeybenfitsmodel',
            name='keybenfit_tags',
        ),
        migrations.AddField(
            model_name='indexpageviewmainkeybenfitsmodel',
            name='keybenfit_icon',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Key benfit icon'),
        ),
    ]
