# Generated by Django 3.2 on 2022-02-15 04:19

import Apps.Index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0033_auto_20220215_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpageqamodel',
            name='qa_extra',
            field=models.JSONField(default=Apps.Index.models.getJSONFieldDefault, verbose_name='QA extra'),
        ),
    ]
