# Generated by Django 3.2 on 2022-02-15 15:48

import Apps.Index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0035_indexnavbar_navbar_subs'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSocialNavbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('social_navbar_title', models.CharField(default='', max_length=16, verbose_name='Social navbar title')),
                ('social_navbar_url', models.CharField(blank=True, default='', max_length=256, verbose_name='Social navbar url')),
                ('social_navbar_icon', models.CharField(blank=True, default='', max_length=32, verbose_name='Social navbar icon')),
                ('social_navbar_subs', models.JSONField(blank=True, default=Apps.Index.models.getJSONFieldDefault, verbose_name='Social navbar subs')),
                ('social_navbar_display', models.BooleanField(default=True, verbose_name='Navbar status')),
            ],
            options={
                'verbose_name': 'social_navbar',
                'verbose_name_plural': 'social_navbar',
                'db_table': 'armod_index_social_navbar_test',
            },
        ),
    ]
