# Generated by Django 3.2 on 2022-02-16 04:59

import Apps.Index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0036_indexsocialnavbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpageviewkeybenfitsmodel',
            name='keybenfit_tags',
            field=models.JSONField(blank=True, default=Apps.Index.models.getJSONFieldDefault, verbose_name='Key benfit tags'),
        ),
    ]
