"""
Django settings for ARMODServers project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import sys
SITE_ID = 1

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, os.path.join(BASE_DIR, 'Apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+7@qig2s8elk5ia4l6enph^j6)-*+ky$k1(yo#(7v%9+lzr7tz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'Apps.Users',
    'Apps.Applications',
    'Apps.ARExperiences',
    'Apps.TagManager',
    'Apps.ARShowcasesCenter',
    'Apps.Api',
    'Apps.Apiv2',
    'Apps.Index',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'ARMODServers.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ARMODServers.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': ['rest_framework.parsers.JSONParser',
                               'rest_framework.parsers.FormParser',
                               'rest_framework.parsers.MultiPartParser',],
    'DEFAULT_AUTHENTICATION_CLASSES': ['Api.utils.Authtication', ],
    'DEFAULT_THROTTLE_CLASSES': [
        'Api.utils.VisitThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',


    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10000/day',
        'user': '10000/day',
        'api': '10000/day'
    },
    'DEFAULT_PAGINATION_CLASS':  'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10 
}


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'DB_NAME',
        'USER': 'USER_NAME',
        'PASSWORD': 'PASSWORD',
        'HOST': 'YOUR_HOST', 
        'PORT': '3306',
        'OPTIONS': {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Model class used by django authentication system
AUTHENTICATION_BACKENDS = (
    'Users.views.CustomBackend',
)

AUTH_USER_MODEL = 'Users.User'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_collections')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]


# Media file path
MEDIA_ROOT = os.path.join(BASE_DIR, 'meida')
IMAGE_ROOT = os.path.join(MEDIA_ROOT, 'images')
IMAGE_URL = 'images'
AREXPERIENCE_ROOT = os.path.join(MEDIA_ROOT, 'arexperiences')
AREXPERIENCE_URL = 'arexperiences'

# Aliyun OSS
OSS_ACCESS_KEY_ID = "YOUR_OSS_ACCESS_KEY_ID"
OSS_ACCESS_KEY_SECRET = "YOUR_OSS_ACCESS_KEY_SECRET"
OSS_ENDPOINT="YOUR_OSS_END_POINT"
OSS_BUCKET_NAME = "YOUR_BUCKET_NAME"
ALIYUN_OSS_ACCESS_URL = 'YOUR_ALIYUN_OSS_ACCESS_URL'
OSS_BASE_URL = 'YOUR_OSS_BASE_URL'
BASE_WEBSITE_URL= 'YOUR_DOMAIN_URL'

# Email config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Whether to use TLS secure transmission protocol (used to provide confidentiality and data integrity between two communication applications.)
EMAIL_USE_TLS = False                    # Use TLS
EMAIL_USE_SSL = True                     # Use SSL
EMAIL_HOST = 'YOUR_SMTP_SERVER'          # SMTP server
EMAIL_PORT = 465                         # SMTP server port
EMAIL_HOST_USER = 'YOUR_SENDER_EMAIL'    # Sender
EMAIL_HOST_PASSWORD = 'YOUR_PASSWORD'    # Password
EMAIL_PROM = 'YOUR_SENDER_INFOMATION'    # Sender infomation, e.g. ARMOD<no-reply@phantonsxr.com>


# Django's cache configuration, use redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# Session cache
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
# Redis Cache expiration time
API_CACHE_EXPIRED = 3600

# Login url address
LOGIN_URL = '/auth/login'