# Generated by Django 3.1.6 on 2021-04-13 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arshowcasescentermodel',
            name='showcase_tags',
        ),
    ]
