# Generated by Django 3.1.4 on 2021-04-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0002_remove_arshowcasescentermodel_showcase_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='app_uid',
            field=models.IntegerField(db_index=True, default=-1, verbose_name='App uid'),
        ),
    ]
