# Generated by Django 3.1.4 on 2021-04-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0003_auto_20210413_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arshowcasescentertagsmodel',
            name='tag_name',
            field=models.CharField(db_index=True, default='', max_length=16, verbose_name='Tag name'),
        ),
    ]
