# Generated by Django 3.1.4 on 2021-04-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0004_auto_20210413_2140'),
    ]

    operations = [
        migrations.RenameModel('ARShowcasesCenterTagsModel', 'ARShowcasesAndTagsLinkModel')
    ]