# Generated by Django 3.1.4 on 2021-04-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0005_auto_20210413_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARShowcasesTagsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('tag_name', models.CharField(db_index=True, default='', max_length=16, unique=True, verbose_name='Tag name')),
            ],
            options={
                'verbose_name': 'Showcases tags',
                'verbose_name_plural': 'Showcases tags',
                'db_table': 'armod_showcases_tags',
            },
        ),
        migrations.AlterModelOptions(
            name='arshowcasesandtagslinkmodel',
            options={'verbose_name': 'Showcases tags link', 'verbose_name_plural': 'Showcases tags link'},
        ),
        migrations.AlterModelTable(
            name='arshowcasesandtagslinkmodel',
            table='armod_showcases_tags_link',
        ),
    ]
