# Generated by Django 3.1.6 on 2021-04-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0006_auto_20210413_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='arshowcasesandtagslinkmodel',
            name='app_uid',
            field=models.IntegerField(db_index=True, default=-1, verbose_name='App uid'),
        ),
        migrations.AddField(
            model_name='arshowcasesandtagslinkmodel',
            name='user_uid',
            field=models.IntegerField(db_index=True, default=-1, verbose_name='User uid'),
        ),
        migrations.AddField(
            model_name='arshowcasestagsmodel',
            name='app_uid',
            field=models.IntegerField(db_index=True, default=-1, verbose_name='App uid'),
        ),
        migrations.AddField(
            model_name='arshowcasestagsmodel',
            name='user_uid',
            field=models.IntegerField(db_index=True, default=-1, verbose_name='User uid'),
        ),
    ]
