# Generated by Django 3.1.6 on 2021-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0008_arshowcasestagsmodel_tag_sort_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='arshowcasestagsmodel',
            name='tag_reference_weight',
            field=models.IntegerField(db_index=True, default=-1, verbose_name='reference'),
        ),
    ]
