# Generated by Django 3.1.6 on 2021-04-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0009_arshowcasestagsmodel_tag_reference_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arshowcasestagsmodel',
            name='tag_reference_weight',
            field=models.IntegerField(db_index=True, default=0, verbose_name='reference'),
        ),
    ]
