# Generated by Django 3.1.4 on 2021-04-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0010_auto_20210415_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='arshowcasescentermodel',
            name='showcase_brief',
            field=models.CharField(default='', max_length=64,  verbose_name='Showcase brief'),
        ),
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='showcase_name',
            field=models.CharField(default='', max_length=16, unique=True, verbose_name='Showcase name'),
        ),
    ]
