# Generated by Django 3.1.4 on 2021-04-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0011_auto_20210418_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='showcase_brief',
            field=models.CharField(default='', max_length=64, verbose_name='Showcase brief'),
        ),
    ]
