# Generated by Django 3.1.4 on 2021-04-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0012_auto_20210418_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='arshowcasescentermodel',
            name='showcase_permission',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Showcase permission'),
        ),
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='showcase_name',
            field=models.CharField(db_index=True, default='', max_length=16, unique=True, verbose_name='Showcase name'),
        ),
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='showcase_status',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Showcase status'),
        ),
    ]
