# Generated by Django 3.1.4 on 2021-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0014_auto_20210418_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arshowcasesandtagslinkmodel',
            name='app_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='App uid'),
        ),
        migrations.AlterField(
            model_name='arshowcasesandtagslinkmodel',
            name='showcase_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='Showcases uid'),
        ),
        migrations.AlterField(
            model_name='arshowcasesandtagslinkmodel',
            name='user_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='User uid'),
        ),
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='app_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='App uid'),
        ),
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='arexperience_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='ARExperience uid'),
        ),
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='user_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='User uid'),
        ),
        migrations.AlterField(
            model_name='arshowcasestagsmodel',
            name='app_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='App uid'),
        ),
        migrations.AlterField(
            model_name='arshowcasestagsmodel',
            name='user_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='User uid'),
        ),
    ]
