# Generated by Django 3.1.4 on 2021-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0015_auto_20210419_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='showcase_header',
            field=models.CharField(default='', max_length=512, verbose_name='Showcase header'),
        ),
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='showcase_icon',
            field=models.CharField(default='', max_length=512, verbose_name='Showcase icon'),
        ),
    ]
