# Generated by Django 3.1.6 on 2021-05-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0017_auto_20210421_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='arshowcasescentermodel',
            name='showcase_recommend',
            field=models.BooleanField(default=False, verbose_name='Showcase recommend'),
        ),
    ]
