# Generated by Django 3.1.6 on 2021-05-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0018_arshowcasescentermodel_showcase_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='showcase_recommend',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Showcase recommend'),
        ),
    ]
