# Generated by Django 3.2 on 2021-05-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0030_auto_20210503_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='arshowcasescentermodel',
            name='showcase_tags_json',
            field=models.JSONField(default=[]),
        ),
    ]
