# Generated by Django 3.2 on 2021-05-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0031_arshowcasescentermodel_showcase_tags_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arshowcasescentermodel',
            name='showcase_not_index_tags',
        ),
        migrations.RemoveField(
            model_name='arshowcasescentermodel',
            name='showcase_tags_json',
        ),
    ]
