# Generated by Django 3.2 on 2021-05-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0032_auto_20210503_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='arshowcasescentermodel',
            name='showcase_not_index_tags',
            field=models.JSONField(default=[], verbose_name='Showcase not index tags'),
        ),
    ]
