# Generated by Django 3.2 on 2021-05-04 10:34

import Apps.ARShowcasesCenter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0033_arshowcasescentermodel_showcase_not_index_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='showcase_not_index_tags',
            field=models.JSONField(default=Apps.ARShowcasesCenter.models.getJSONFieldDefault, verbose_name='Showcase not index tags'),
        ),
    ]
