# Generated by Django 3.2 on 2022-03-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARShowcasesCenter', '0034_alter_arshowcasescentermodel_showcase_not_index_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arshowcasesandtagslinkmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='arshowcasesandtagslinkmodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete Flag'),
        ),
        migrations.AlterField(
            model_name='arshowcasesandtagslinkmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete Flag'),
        ),
        migrations.AlterField(
            model_name='arshowcasescentermodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='arshowcasestagsmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='arshowcasestagsmodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete Flag'),
        ),
        migrations.AlterField(
            model_name='arshowcasestagsmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time'),
        ),
    ]
