# Generated by Django 3.1.4 on 2021-04-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210411_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pid',
            new_name='user_uid',
        ),
    ]
