# Generated by Django 3.1.4 on 2021-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20210413_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='用户个人Id'),
        ),
    ]
