# Generated by Django 3.2 on 2022-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('user_uid', models.BigIntegerField(db_index=True, default=-1, verbose_name='User uid')),
                ('app_uid', models.BigIntegerField(db_index=True, default=-1, verbose_name='App uid')),
                ('tag_reference_weight', models.IntegerField(default=0, verbose_name='reference')),
                ('tag_sort_weight', models.IntegerField(default=-1, verbose_name='Sort weight')),
                ('tag_name', models.CharField(db_index=True, default='', max_length=16, unique=True, verbose_name='Tag name')),
            ],
            options={
                'verbose_name': 'Tag_Manager_Test',
                'verbose_name_plural': 'Tag_Manager_Test',
                'db_table': 'armod_tags_test',
            },
        ),
    ]
