# Generated by Django 3.2 on 2022-02-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TagManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsmodel',
            name='tag_name',
            field=models.CharField(blank=True, db_index=True, max_length=16, verbose_name='Tag name'),
        ),
    ]
