# Generated by Django 3.2 on 2022-02-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TagManager', '0002_alter_tagsmodel_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsmodel',
            name='tag_key',
            field=models.CharField(db_index=True, default='', max_length=32, verbose_name='Tag key'),
        ),
    ]
