# Generated by Django 3.2 on 2022-02-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TagManager', '0003_tagsmodel_tag_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagsmodel',
            options={'verbose_name': 'Tag_Manager_V2', 'verbose_name_plural': 'Tag_Manager_V2'},
        ),
        migrations.AlterModelTable(
            name='tagsmodel',
            table='armod_tags_v2',
        ),
    ]
