# Generated by Django 3.2 on 2022-03-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TagManager', '0004_auto_20220216_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='tagsmodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete Flag'),
        ),
        migrations.AlterField(
            model_name='tagsmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time'),
        ),
    ]
