# Generated by Django 3.1.4 on 2021-04-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0005_auto_20210411_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='applicationsmodel',
            name='userid',
        ),
        migrations.AddField(
            model_name='applicationsmodel',
            name='appid',
            field=models.IntegerField(db_index=True, default=-1, primary_key=True, serialize=False, verbose_name='应用Id'),
        ),
        migrations.AddField(
            model_name='applicationsmodel',
            name='pid',
            field=models.IntegerField(db_index=True, default=-1, verbose_name='用户Id'),
        ),
    ]
