# Generated by Django 3.1.6 on 2021-04-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0007_auto_20210411_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsmodel',
            name='description',
            field=models.CharField(default='', max_length=128, verbose_name='应用绑定的包名'),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='token',
            field=models.CharField(default='', max_length=128, verbose_name='应用用Token'),
        ),
    ]
