# Generated by Django 3.1.6 on 2021-04-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0008_auto_20210412_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsmodel',
            name='token',
            field=models.CharField(default='', max_length=256, verbose_name='应用用Token'),
        ),
    ]
