# Generated by Django 3.1.4 on 2021-04-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0009_auto_20210413_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationsmodel',
            options={'verbose_name': 'Applications', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelTable(
            name='applicationsmodel',
            table='armod_applications',
        ),
    ]
