# Generated by Django 3.2 on 2022-03-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0011_auto_20210419_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsModelV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Flag')),
                ('app_uid', models.BigIntegerField(db_index=True, default=-1, unique=True, verbose_name='App Id')),
                ('user_uid', models.BigIntegerField(db_index=True, default=-1, verbose_name='User Id')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='App Name')),
                ('packageid', models.CharField(db_index=True, max_length=64, verbose_name='Package Name')),
                ('description', models.CharField(default='', max_length=128, verbose_name='App Description')),
                ('token', models.CharField(default='', max_length=256, verbose_name='License Token')),
                ('app_icon_image', models.CharField(default='', max_length=128, verbose_name='App icon')),
                ('child_project', models.IntegerField(default=0, verbose_name='Project Count')),
            ],
            options={
                'verbose_name': 'Applications_V2',
                'verbose_name_plural': 'Applications_V2',
                'db_table': 'armod_applications_v2',
            },
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='app_uid',
            field=models.BigIntegerField(db_index=True, default=-1, primary_key=True, serialize=False, verbose_name='App Id'),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='child_project',
            field=models.IntegerField(default=0, verbose_name='Project Count'),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='description',
            field=models.CharField(default='', max_length=128, verbose_name='App Description'),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete Flag'),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='name',
            field=models.CharField(max_length=64, verbose_name='App Name'),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='packageid',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Package Name'),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='token',
            field=models.CharField(default='', max_length=256, verbose_name='License Token'),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='applicationsmodel',
            name='user_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='User Id'),
        ),
    ]
