# Generated by Django 3.1.4 on 2021-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARExperienceAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('arexperience_id', models.IntegerField(default=-1, verbose_name='所属项目的Id')),
                ('android_json', models.CharField(max_length=128, verbose_name='android json')),
                ('android_bundle', models.CharField(max_length=128, verbose_name='android bundle')),
                ('android_bundle_size', models.IntegerField(default=-1, verbose_name='android bundle size')),
                ('ios_json', models.CharField(max_length=128, verbose_name='ios json')),
                ('ios_bundle', models.CharField(max_length=128, verbose_name='ios bundle')),
                ('ios_bundle_size', models.IntegerField(default=-1, verbose_name='ios bundle size')),
            ],
            options={
                'verbose_name': 'AR体验资源信息',
                'verbose_name_plural': 'AR体验资源信息',
                'db_table': 'armod_arexperience_assets',
            },
        ),
        migrations.CreateModel(
            name='ARExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('appid', models.IntegerField(default=-1, verbose_name='所属应用的Id')),
                ('status', models.IntegerField(default=1, verbose_name='项目状态')),
            ],
            options={
                'verbose_name': 'AR体验项目信息',
                'verbose_name_plural': 'AR体验项目信息',
                'db_table': 'armod_arexperiences',
            },
        ),
    ]
