# Generated by Django 3.1.6 on 2021-04-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexperiencemodel',
            name='description',
            field=models.CharField(default='', max_length=128, verbose_name='项目描述'),
        ),
    ]
