# Generated by Django 3.1.4 on 2021-04-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0003_auto_20210410_2335'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='arexperiencemodel',
            name='pid',
            field=models.IntegerField(db_index=True, default=-1, primary_key=False, serialize=False, verbose_name='AR体验项目的ID'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='arexperience_id',
            field=models.IntegerField(db_index=True, default=-1, verbose_name='所属项目的Id'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='appid',
            field=models.IntegerField(db_index=True, default=-1, verbose_name='所属应用的Id'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='status',
            field=models.IntegerField(db_index=True, default=1, verbose_name='项目状态'),
        ),
    ]
