# Generated by Django 3.1.4 on 2021-04-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0004_auto_20210411_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arexperienceasset',
            old_name='arexperience_id',
            new_name='pid',
        ),
    ]
