# Generated by Django 3.1.4 on 2021-04-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0005_auto_20210411_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='项目名称'),
        ),
    ]
