# Generated by Django 3.1.4 on 2021-04-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0006_auto_20210411_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arexperienceasset',
            old_name='pid',
            new_name='arexperience_uid',
        ),
        migrations.RenameField(
            model_name='arexperiencemodel',
            old_name='appid',
            new_name='app_uid',
        ),
        migrations.RenameField(
            model_name='arexperiencemodel',
            old_name='pid',
            new_name='arexperience_uid',
        ),
    ]
