# Generated by Django 3.1.4 on 2021-04-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0007_auto_20210411_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arexperienceasset',
            options={'verbose_name': 'ARExperience Assets', 'verbose_name_plural': 'ARExperience Assets'},
        ),
        migrations.AlterModelOptions(
            name='arexperiencemodel',
            options={'verbose_name': 'AR Experiences', 'verbose_name_plural': 'AR Experiences'},
        ),
    ]
