# Generated by Django 3.1.4 on 2021-04-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0008_auto_20210413_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arexperiencemodel',
            options={'verbose_name': 'ARExperiences', 'verbose_name_plural': 'ARExperiences'},
        ),
    ]
