# Generated by Django 3.1.4 on 2021-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0009_auto_20210413_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperienceasset',
            name='android_bundle_size',
            field=models.FloatField(default=-1, verbose_name='android bundle size'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='ios_bundle_size',
            field=models.FloatField(default=-1, verbose_name='ios bundle size'),
        ),
    ]
