# Generated by Django 3.1.4 on 2021-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0010_auto_20210416_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperienceasset',
            name='arexperience_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='所属项目的Id'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='app_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='所属应用的Id'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='arexperience_uid',
            field=models.BigIntegerField(db_index=True, default=-1, primary_key=True, serialize=False, verbose_name='AR体验项目的ID'),
        ),
    ]
