# Generated by Django 3.2 on 2022-02-01 10:39

import Apps.ARExperiences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0011_auto_20210419_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARExperienceModelNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('user_uid', models.BigIntegerField(db_index=True, default=-1, verbose_name='User uid')),
                ('showcase_uid', models.BigIntegerField(db_index=True, default=-1, unique=True, verbose_name='Showcase uid')),
                ('showcase_name', models.CharField(db_index=True, default='', max_length=16, unique=True, verbose_name='Showcase name')),
                ('showcase_brief', models.CharField(default='', max_length=64, verbose_name='Showcase brief')),
                ('showcase_status', models.IntegerField(db_index=True, default=0, verbose_name='Showcase status')),
                ('showcase_permission', models.IntegerField(db_index=True, default=1, verbose_name='Showcase permission')),
                ('showcase_icon', models.CharField(default='', max_length=512, verbose_name='Showcase icon')),
                ('showcase_header', models.CharField(default='', max_length=512, verbose_name='Showcase header')),
                ('showcase_preview', models.CharField(default='', max_length=1024, verbose_name='Showcase previews(json)')),
                ('showcase_description', models.CharField(default='', max_length=1024, verbose_name='Showcase description')),
                ('showcase_recommend', models.BooleanField(db_index=True, default=False, verbose_name='Showcase recommend')),
                ('showcase_not_index_tags', models.JSONField(default=Apps.ARExperiences.models.getJSONFieldDefault, verbose_name='Showcase not index tags')),
                ('showcase_weight', models.IntegerField(db_index=True, default=0, verbose_name='Showcase Weight')),
            ],
            options={
                'verbose_name': 'ARExperiences202202',
                'verbose_name_plural': 'ARExperiences202202',
                'db_table': 'armod_arexperiences_202202',
            },
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='arexperience_uid',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='所属项目的Id'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='arexperience_uid',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='所属项目的Id'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
