# Generated by Django 3.2 on 2022-03-21 08:48

import Apps.ARExperiences.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0011_auto_20210419_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARExperienceModelV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Flag')),
                ('app_uid', models.BigIntegerField(db_index=True, default=-1, verbose_name='AR Experience Id')),
                ('user_uid', models.BigIntegerField(db_index=True, default=-1, verbose_name='User uid')),
                ('project_id', models.BigIntegerField(db_index=True, default=-1, unique=True, verbose_name='Showcase uid')),
                ('project_name', models.CharField(db_index=True, default='', max_length=16, unique=True, verbose_name='Showcase name')),
                ('project_brief', models.CharField(default='', max_length=64, verbose_name='Showcase brief')),
                ('project_status', models.IntegerField(db_index=True, default=0, verbose_name='Showcase status')),
                ('project_permission', models.IntegerField(db_index=True, default=1, verbose_name='Showcase permission')),
                ('project_icon', models.CharField(default='', max_length=512, verbose_name='Showcase icon')),
                ('project_header', models.CharField(default='', max_length=512, verbose_name='Showcase header')),
                ('project_preview', models.CharField(default='', max_length=1024, verbose_name='Showcase previews(json)')),
                ('project_description', models.CharField(blank=True, default='', max_length=1024, verbose_name='Showcase description')),
                ('project_recommend', models.BooleanField(db_index=True, default=False, verbose_name='Showcase recommend')),
                ('project_tags', models.JSONField(default=Apps.ARExperiences.models.getJSONFieldDefault, verbose_name='Showcase not index tags')),
                ('project_weight', models.IntegerField(db_index=True, default=0, verbose_name='Showcase Weight')),
            ],
            options={
                'verbose_name': 'ARExperiences_V2',
                'verbose_name_plural': 'ARExperiences_V2',
                'db_table': 'armod_arexperiences_v2',
            },
        ),
        migrations.CreateModel(
            name='ARExperienceResourceV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Delete Flag')),
                ('project_id', models.BigIntegerField(db_index=True, null=True, verbose_name='AR Experience Id')),
                ('json_url', models.CharField(max_length=128, verbose_name='android json')),
                ('bundle_url', models.CharField(max_length=128, verbose_name='android bundle')),
                ('bundle_size', models.FloatField(default=-1, verbose_name='android bundle size')),
                ('platform_type', models.CharField(max_length=16, verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'ARExperienceAssets_V2',
                'verbose_name_plural': 'ARExperienceAssets_V2',
                'db_table': 'armod_arexperience_assets_v2',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv', models.IntegerField(default=0, verbose_name='UV')),
                ('uv', models.IntegerField(default=0, verbose_name='PV')),
                ('date', models.CharField(max_length=200)),
                ('project_id', models.BigIntegerField(db_index=True, null=True, verbose_name='AR Experience Id')),
            ],
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='android_bundle',
            field=models.CharField(max_length=128, verbose_name='Android Bundle'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='android_bundle_size',
            field=models.FloatField(default=-1, verbose_name='Android Bundle Size'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='android_json',
            field=models.CharField(max_length=128, verbose_name='Android Json'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='arexperience_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='AR Experience Id'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='ios_bundle',
            field=models.CharField(max_length=128, verbose_name='iOS Bundle'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='ios_bundle_size',
            field=models.FloatField(default=-1, verbose_name='iOS Bundle Size'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='ios_json',
            field=models.CharField(max_length=128, verbose_name='iOS Json'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete Flag'),
        ),
        migrations.AlterField(
            model_name='arexperienceasset',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='app_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='App Id'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='arexperience_uid',
            field=models.BigIntegerField(db_index=True, default=-1, primary_key=True, serialize=False, verbose_name='AR Experience Id'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='description',
            field=models.CharField(default='', max_length=128, verbose_name='AR Experience Descriptor'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Delete Flag'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='AR Experience Name'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='status',
            field=models.IntegerField(db_index=True, default=1, verbose_name='AR Experience Project Status'),
        ),
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time'),
        ),
    ]
