# Generated by Django 3.2 on 2022-02-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0012_auto_20220201_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='arexperience_uid',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='AR体验项目的ID'),
        ),
    ]
