# Generated by Django 3.2 on 2022-02-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0014_alter_arexperiencemodel_arexperience_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperiencemodel',
            name='arexperience_uid',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='AR体验项目的ID'),
        ),
    ]
