# Generated by Django 3.2 on 2022-02-01 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0016_arexperiencemodeltest'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexperiencemodeltest',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ARExperiences.arexperiencemodelnew'),
        ),
    ]
