# Generated by Django 3.2 on 2022-02-01 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0019_auto_20220201_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arexperiencemodelnew',
            name='detail',
        ),
        migrations.AddField(
            model_name='arexperiencemodeltest',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ARExperiences.arexperiencemodelnew'),
        ),
    ]
