# Generated by Django 3.2 on 2022-02-02 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0021_auto_20220201_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARExperienceResourceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('arexperience_uid', models.BigIntegerField(db_index=True, null=True, verbose_name='所属项目的Id')),
                ('json_file', models.CharField(max_length=128, verbose_name='android json')),
                ('bundle_file', models.CharField(max_length=128, verbose_name='android bundle')),
                ('bundle_size', models.FloatField(default=-1, verbose_name='android bundle size')),
                ('platform_type', models.CharField(max_length=16, verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'ARExperienceAssetsTest',
                'verbose_name_plural': 'ARExperienceAssetsTest',
                'db_table': 'armod_arexperience_assets_test',
            },
        ),
        migrations.RemoveField(
            model_name='arexperiencemodeltest',
            name='app_uid',
        ),
        migrations.RemoveField(
            model_name='arexperiencemodeltest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='arexperiencemodeltest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='arexperiencemodeltest',
            name='status',
        ),
        migrations.AddField(
            model_name='arexperiencemodelnew',
            name='app_uid',
            field=models.BigIntegerField(db_index=True, default=-1, verbose_name='所属应用的Id'),
        ),
        migrations.AddField(
            model_name='arexperiencemodeltest',
            name='arexperience_resource',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ARExperiences.arexperienceresourcetest'),
        ),
    ]
