# Generated by Django 3.2 on 2022-02-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0022_auto_20220202_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arexperiencemodelnew',
            name='detail',
        ),
        migrations.AddField(
            model_name='arexperiencemodelnew',
            name='resources',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ARExperiences.arexperienceresourcetest'),
        ),
        migrations.DeleteModel(
            name='ARExperienceModelTest',
        ),
    ]
