# Generated by Django 3.2 on 2022-02-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0023_auto_20220202_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARExperienceResourceCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('platform_resources', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_resources', to='ARExperiences.arexperienceresourcetest')),
            ],
            options={
                'verbose_name': 'ARExperiencesCollectionTest',
                'verbose_name_plural': 'ARExperiencesCollectionTest',
                'db_table': 'armod_arexperiences_collection_test',
            },
        ),
        migrations.AlterField(
            model_name='arexperiencemodelnew',
            name='resources',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ARExperiences.arexperienceresourcecollection'),
        ),
    ]
