# Generated by Django 3.2 on 2022-02-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0024_auto_20220202_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arexperiencemodelnew',
            name='resources',
        ),
    ]
