# Generated by Django 3.2 on 2022-02-02 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0025_remove_arexperiencemodelnew_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='arexperiencemodelnew',
            name='resources',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ARExperiences.arexperienceresourcecollection'),
        ),
    ]
