# Generated by Django 3.2 on 2022-02-02 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0026_arexperiencemodelnew_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arexperiencemodelnew',
            name='resources',
        ),
        migrations.AddField(
            model_name='arexperienceresourcetest',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='ARExperiences.arexperiencemodelnew'),
        ),
        migrations.DeleteModel(
            name='ARExperienceResourceCollection',
        ),
    ]
