# Generated by Django 3.2 on 2022-02-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0027_auto_20220202_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arexperienceresourcetest',
            name='project',
        ),
    ]
