# Generated by Django 3.2 on 2022-02-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0029_alter_arexperienceresourcetest_arexperience_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_brief',
            new_name='project_brief',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_header',
            new_name='project_header',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_icon',
            new_name='project_icon',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_uid',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_permission',
            new_name='project_permission',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_preview',
            new_name='project_preview',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_recommend',
            new_name='project_recommend',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_status',
            new_name='project_status',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_not_index_tags',
            new_name='project_tags',
        ),
        migrations.RenameField(
            model_name='arexperiencemodelnew',
            old_name='showcase_weight',
            new_name='project_weight',
        ),
        migrations.RenameField(
            model_name='arexperienceresourcetest',
            old_name='bundle_file',
            new_name='bundle_url',
        ),
        migrations.RenameField(
            model_name='arexperienceresourcetest',
            old_name='json_file',
            new_name='json_url',
        ),
        migrations.RenameField(
            model_name='arexperienceresourcetest',
            old_name='arexperience_uid',
            new_name='project_uid',
        ),
    ]
