# Generated by Django 3.2 on 2022-02-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0031_rename_project_uid_arexperienceresourcetest_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperienceresourcetest',
            name='project_id',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='所属项目的Id'),
        ),
    ]
