# Generated by Django 3.2 on 2022-02-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0032_alter_arexperienceresourcetest_project_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ARExperienceModelNew',
            new_name='ARExperienceModelTest',
        ),
        migrations.AlterModelOptions(
            name='arexperiencemodeltest',
            options={'verbose_name': 'ARExperiences_Test', 'verbose_name_plural': 'ARExperiences_Test'},
        ),
        migrations.AlterModelOptions(
            name='arexperienceresourcetest',
            options={'verbose_name': 'ARExperienceAssets_Test', 'verbose_name_plural': 'ARExperienceAssets_Test'},
        ),
        migrations.AlterModelTable(
            name='arexperiencemodeltest',
            table='armod_arexperiences_test',
        ),
    ]
