# Generated by Django 3.2 on 2022-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0033_auto_20220205_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('uv', models.IntegerField(default=0, verbose_name='浏览人数')),
                ('date', models.CharField(max_length=200)),
                ('project_id', models.BigIntegerField(db_index=True, null=True, verbose_name='所属项目的Id')),
            ],
        ),
    ]
