# Generated by Django 3.2 on 2022-02-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0034_statistics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ARExperienceModelTest',
            new_name='ARExperienceModelV2',
        ),
        migrations.RenameModel(
            old_name='ARExperienceResourceTest',
            new_name='ARExperienceResourceV2',
        ),
        migrations.AlterModelOptions(
            name='arexperiencemodelv2',
            options={'verbose_name': 'ARExperiences_V2', 'verbose_name_plural': 'ARExperiences_V2'},
        ),
        migrations.AlterModelOptions(
            name='arexperienceresourcev2',
            options={'verbose_name': 'ARExperienceAssets_V2', 'verbose_name_plural': 'ARExperienceAssets_V2'},
        ),
        migrations.AlterModelTable(
            name='arexperiencemodelv2',
            table='armod_arexperiences_v2',
        ),
        migrations.AlterModelTable(
            name='arexperienceresourcev2',
            table='armod_arexperience_assets_v2',
        ),
    ]
