# Generated by Django 3.2 on 2022-02-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARExperiences', '0035_auto_20220216_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arexperiencemodelv2',
            name='project_description',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Showcase description'),
        ),
    ]
